import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { createSupportTicket, trackProductEvent } from '@/services/SelfServiceService';

export default function SupportPage() {
  const [form, setForm] = useState({ name: '', email: '', subject: '', category: 'general', message: '', website: '' });
  const [error, setError] = useState(''); const [ticket, setTicket] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void trackProductEvent('contact_started'); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = await createSupportTicket(form); setTicket(result.ticket_number || 'received'); } catch (err) { setError(err instanceof Error ? err.message : 'Could not send request'); } finally { setBusy(false); } }
  return <main><section><Link href="/" className="brand">Smartdok.ai</Link><h1>How can we help?</h1><p>Send our team the details. We’ll keep everything under one trackable reference.</p>{ticket ? <div className="success"><h2>Request received</h2><p>Your reference is <strong>{ticket}</strong>. Keep it handy when following up.</p></div> : <form onSubmit={submit}>{error && <div className="error">{error}</div>}<div className="row"><input required placeholder="Name" value={form.name} onChange={e => setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></div><input required minLength={3} placeholder="Subject" value={form.subject} onChange={e => setForm({...form,subject:e.target.value})}/><select value={form.category} onChange={e => setForm({...form,category:e.target.value})}><option value="general">General</option><option value="sales">Sales</option><option value="billing">Billing</option><option value="technical">Technical issue</option><option value="security">Security</option><option value="privacy">Privacy</option></select><textarea required minLength={10} rows={7} placeholder="What happened, and what were you trying to do?" value={form.message} onChange={e => setForm({...form,message:e.target.value})}/><input className="honeypot" tabIndex={-1} autoComplete="off" value={form.website} onChange={e => setForm({...form,website:e.target.value})}/><button disabled={busy}>{busy?'Sending…':'Send request'}</button></form>}</section><style jsx>{`main{min-height:100vh;background:#f8fafc;padding:60px 20px;font-family:Inter,system-ui;color:#0f172a}section{max-width:650px;margin:auto;background:white;border:1px solid #e2e8f0;border-radius:22px;padding:36px}.brand{font-weight:800;color:#0f172a;text-decoration:none}h1{font-size:34px;margin-bottom:6px}p{color:#64748b;line-height:1.55}form{display:grid;gap:13px;margin-top:24px}.row{display:grid;grid-template-columns:1fr 1fr;gap:13px}input,select,textarea,button{font:inherit;padding:12px;border-radius:10px;border:1px solid #cbd5e1}button{border:0;background:#2563eb;color:#fff;font-weight:750}.honeypot{position:absolute;left:-9999px}.error{color:#b91c1c;background:#fef2f2;padding:10px;border-radius:8px}.success{background:#ecfdf5;padding:20px;border-radius:12px;margin-top:24px}@media(max-width:550px){.row{grid-template-columns:1fr}}`}</style></main>;
}
